soring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

spring:
  jpa:
    hibernate:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://awsnamesdb.cdpt9yr9jxab.us-east-2.rds.amazonaws.com:3306/coursenamedb
    username: admindb
    password: course123
    pool-size: 30
